name: todo_app
description: "A simple todo app"
publish_to: "none"
version: 1.0.0

environment:
    sdk: ">=3.11.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    google_fonts: ^8.0.2
    firebase_core: ^4.4.0
    firebase_auth: ^6.1.4
    cloud_firestore: ^6.1.2
    json_annotation: ^4.9.0
    flutter_screenutil: ^5.9.0
    flutter_local_notifications: ^20.1.0
    flutter_slidable: ^4.0.0
    easy_date_timeline: ^2.0.9
    gap: ^3.0.1
    animated_list_plus: ^0.5.2
    intl: ^0.20.2
    entry: ^1.0.0
    flutter_riverpod: ^3.1.0
    riverpod_annotation: ^4.0.0
    confetti: 0.8.0

dev_dependencies:
    flutter_lints: ^6.0.0
    flutter_launcher_icons: ^0.14.3
    build_runner: ^2.11.1
    json_serializable: ^6.11.2
    riverpod_generator: ^4.0.0+1
    riverpod_lint: ^3.1.0
    custom_lint: ^0.8.1

flutter:
    uses-material-design: true
    assets:
        - assets/

flutter_launcher_icons:
    ios: true
    android: true
    remove_alpha_ios: true
    image_path: "assets/todo_app_icon.png"
